import { TrainingPattern, Exercise } from '@/types';

export const SLIDE_IMAGES = [
  'https://i.pinimg.com/736x/14/7b/c4/147bc4f93a10432f2f41f3ea28acce01.jpg',
  'https://i.pinimg.com/736x/1c/c7/f1/1cc7f11a62d0b4f9fc442217fb729a7b.jpg',
  'https://i.pinimg.com/736x/36/59/e7/3659e7e8a1299632301bf16b9d233780.jpg',
];

export const EX_IMAGES: Record<string, string> = {
  'バーベル・オーバーヘッドプレス': 'https://i.pinimg.com/736x/dd/b6/e5/ddb6e54182373a78bd62695ec1d5989d.jpg',
  'ダンベル・サイドレイズ': 'https://i.pinimg.com/736x/56/f7/e7/56f7e7fd25a0e84ef084f26978008501.jpg',
  'ダンベル・リアレイズ': 'https://i.pinimg.com/736x/22/27/09/2227099f511b5057461f43cfacbfb016.jpg',
  'ショルダー・プレス': 'https://i.pinimg.com/736x/f2/0e/66/f20e660ee3d6f9996a783d3a07537aad.jpg',
  'ダンベル・シュラッグ': 'https://i.pinimg.com/736x/5a/57/19/5a5719671922993782d7a6902d4c28a4.jpg',
  'スミスマシン・スクワット': 'https://i.pinimg.com/736x/a4/26/95/a426959e125a6f0993d1bbfa89306772.jpg',
  'レッグプレス': 'https://i.pinimg.com/736x/7b/67/fc/7b67fc28fe2c712da6c8ded2ea40945e.jpg',
  'レッグカール': 'https://i.pinimg.com/736x/20/bf/99/20bf9951823ccf26e150832b82cab7b1.jpg',
  'レッグエクステンション': 'https://i.pinimg.com/736x/96/e6/a0/96e6a06d48a8531912fa2e0a278b13a1.jpg',
  'カーフレイズ（マシン）': 'https://i.pinimg.com/736x/b5/d0/fb/b5d0fb36a65b432b8b7596c95ae88f15.jpg',
  'デッドリフト': 'https://i.pinimg.com/736x/b7/15/ba/b715ba1e72d575dc6ae3d64acf2a8404.jpg',
  'バーベル・ベントオーバーロウ': 'https://i.pinimg.com/736x/85/e1/65/85e165960d11adfdd302feb3cf2c3676.jpg',
  'ダンベル・ワンハンドロウ': 'https://i.pinimg.com/736x/f3/57/45/f35745176a2fae132d5636e72901f261.jpg',
  'バーベル・グッドモーニング': 'https://i.pinimg.com/736x/ec/96/cc/ec96ccba598b51af0bab08494780f50d.jpg',
  'バーベル・カール': 'https://i.pinimg.com/1200x/e6/27/c2/e627c243532b860a043ee57103c96935.jpg',
  'バーベル・ベンチプレス': 'https://i.pinimg.com/736x/09/4f/1f/094f1f295f293a94598bb2195e3ee53b.jpg',
  'ダンベル・インクラインプレス': 'https://i.pinimg.com/736x/17/89/84/1789841561d6ce2c7af7ef631a83bb9d.jpg',
  'ダンベル・フライ': 'https://i.pinimg.com/736x/0c/18/3b/0c183bfa4885ab92658c812e2a93e690.jpg',
  'ダンベル・サイドレイズ（肩補助）': 'https://i.pinimg.com/736x/56/f7/e7/56f7e7fd25a0e84ef084f26978008501.jpg',
  'ディップス（自重）': 'https://i.pinimg.com/736x/fd/c4/1f/fdc41fdbdb57b198aa026173aada9263.jpg',
  'バーベル・スクワット': 'https://i.pinimg.com/736x/9e/86/98/9e86985a6d540fe69b6bf69a3f412a07.jpg',
  'バーベル・ヒップスラスト': 'https://i.pinimg.com/736x/fb/dd/74/fbdd74095cf2b5caa576a86b16b70410.jpg',
  'ダンベル・ランジ': 'https://i.pinimg.com/736x/b1/0e/c2/b10ec2dc7ea385cdb1de9a34fa3fce1a.jpg',
  'ルーマニアン・デッドリフト': 'https://i.pinimg.com/736x/91/eb/4a/91eb4a8bb224e8130f1ce9c0fb33c957.jpg',
  'カーフレイズ（バーベル）': 'https://i.pinimg.com/736x/72/cb/2a/72cb2af2f6e0e29d6aeaa6ee12ee277e.jpg',
  'スミスマシン・ショルダープレス': 'https://i.pinimg.com/736x/d0/30/60/d03060b599cebb0a9a00444c81ae0318.jpg',
  'マシン・サイドレイズ（またはダンベル）': 'https://i.pinimg.com/736x/d7/a1/69/d7a169af0ed7491391866f69730b2404.jpg',
  'ラットプルダウン': 'https://i.pinimg.com/736x/ca/e3/86/cae38640aa3a16ff2266bf1c7a9144c7.jpg',
};

// ===== SHARED EXERCISES =====

const shoulderExercises: Exercise[] = [
  {
    name: 'バーベル・オーバーヘッドプレス',
    icon: '🔱',
    sets: 4,
    reps: '6〜8rep ／ メイン種目',
    description: '肩の王道種目。全体の三角筋と上部僧帽筋を最大限に刺激。肩の厚みと丸みを作る最重要メニュー。',
    points: [
      'グリップは肩幅より少し広め',
      '体幹をしっかり固めてバーを真上に押す',
      'バーが顎を超えたら頭を少し前に出す',
      '最初の2セットで重量を決める（メインはRPE8程度）',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=バーベルオーバーヘッドプレス+やり方',
    imageUrl: EX_IMAGES['バーベル・オーバーヘッドプレス'],
  },
  {
    name: 'ダンベル・サイドレイズ',
    icon: '↔️',
    sets: 4,
    reps: '12〜15rep ／ 最終セットはドロップ',
    description: '三角筋中部を集中的に鍛える。肩の横の張り出し・服を着たときの肩幅づくりに直結。',
    points: [
      '肘を少し曲げ、小指側を上に向けて上げる',
      '肩より高く上げすぎない（僧帽筋を使いすぎない）',
      'ゆっくり下ろして筋肉に効かせる',
      '最終セットはドロップセット（重量を下げて追い込む）',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルサイドレイズ+コツ',
    imageUrl: EX_IMAGES['ダンベル・サイドレイズ'],
  },
  {
    name: 'ダンベル・リアレイズ',
    icon: '🔙',
    sets: 4,
    reps: '12〜15rep',
    description: '三角筋後部を鍛え、後ろから見たときの肩の丸みとVシェイプを強調。姿勢改善にも効果的。',
    points: [
      '上体を前傾（約45〜90度）させて行う',
      '肘を少し曲げたまま横に広げる',
      '肩甲骨を寄せすぎず、三角筋後部で引く意識',
      '軽めの重量でフォームを優先する',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルリアレイズ+三角筋後部',
    imageUrl: EX_IMAGES['ダンベル・リアレイズ'],
  },
  {
    name: 'ショルダー・プレス',
    icon: '🔄',
    sets: 3,
    reps: '10〜12rep',
    description: 'ダンベルを使って三角筋全体を鍛えるプレス種目。バーベルより可動域が広くコントロールしやすいため、フォームを意識しながら追い込みやすい。',
    points: [
      'ダンベルを耳の高さ・肩幅程度でスタート',
      '頭の真上に向けてまっすぐ押し上げる',
      '最高点で肘をロックせず少し曲げたまま',
      'ゆっくり（2〜3秒）下ろす',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルショルダープレス+三角筋+フォーム',
    imageUrl: EX_IMAGES['ショルダー・プレス'],
  },
  {
    name: 'ダンベル・シュラッグ',
    icon: '⚡',
    sets: 3,
    reps: '12rep ／ 締め種目',
    description: 'ダンベルで僧帽筋（首から肩にかけての筋肉）を鍛える種目。首回りのボリュームアップと肩の安定性向上に効果的。左右個別に動かせるため、左右差の修正にも使いやすい。',
    points: [
      'ダンベルを体の横に持ち、肩を耳に近づけるように真上に引き上げる',
      '最高点で2〜3秒キープして僧帽筋を収縮させる',
      'ゆっくり下ろしてストレッチをしっかり効かせる',
      '首を縮めたり回したりしない',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルシュラッグ+僧帽筋+フォーム',
    imageUrl: EX_IMAGES['ダンベル・シュラッグ'],
  },
];

const machineLegExercises: Exercise[] = [
  {
    name: 'スミスマシン・スクワット',
    icon: '🏔️',
    sets: 4,
    reps: '8〜10rep ／ メイン種目',
    description: 'マシンで安定した軌道を確保しながら大腿四頭筋・大臀筋を重点的に鍛える。',
    points: [
      '足の位置はやや前方（バーの真下より少し前）',
      '膝がつま先より内側に入らないよう注意',
      '太ももが床と平行になるまで下げる',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=スミスマシンスクワット+フォーム',
    imageUrl: EX_IMAGES['スミスマシン・スクワット'],
  },
  {
    name: 'レッグプレス',
    icon: '🦿',
    sets: 4,
    reps: '10〜12rep',
    description: '腰への負担を減らしながら大腿四頭筋・大臀筋・ハムストリングスに高重量をかけられる。',
    points: [
      '足幅はやや広め、つま先は30度外向き',
      '膝がプラットフォームに当たりすぎない深さまで曲げる',
      '腰をシートから浮かさない',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=レッグプレス+やり方+コツ',
    imageUrl: EX_IMAGES['レッグプレス'],
  },
  {
    name: 'レッグカール',
    icon: '🔩',
    sets: 3,
    reps: '12rep',
    description: 'ハムストリングスを単独で鍛えられる貴重な種目。太ももの裏の厚みを作る。',
    points: [
      '骨盤を浮かさずに曲げる',
      '最大収縮でキープ（1〜2秒）',
      'ゆっくり（3秒）伸ばして戻す',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=レッグカール+フォーム',
    imageUrl: EX_IMAGES['レッグカール'],
  },
  {
    name: 'レッグエクステンション',
    icon: '🦵',
    sets: 3,
    reps: '15rep',
    description: '大腿四頭筋を最大収縮まで追い込む仕上げ種目。',
    points: [
      'つま先をやや外向きにすると外側広筋に入りやすい',
      '最高点で1〜2秒キープ',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=レッグエクステンション+コツ',
    imageUrl: EX_IMAGES['レッグエクステンション'],
  },
  {
    name: 'カーフレイズ（マシン）',
    icon: '⬆️',
    sets: 4,
    reps: '15〜20rep',
    description: 'ふくらはぎを鍛えて脚全体のシルエットを完成させる。',
    points: [
      '踵が完全に下がりきる深さまでストレッチ',
      '最高点で2秒キープ',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=カーフレイズ+やり方',
    imageUrl: EX_IMAGES['カーフレイズ（マシン）'],
  },
];

const backBicepExercises: Exercise[] = [
  {
    name: 'デッドリフト',
    icon: '⚓',
    sets: 4,
    reps: '5rep ／ 最重要種目',
    description: '全身の筋肉を動員する最強の種目。背中の厚みとVシェイプ、全体的な筋肉量増加の核心。',
    points: [
      'バーはすねの前（ほぼ密着）、足幅は腰幅',
      '背中をフラットに保ち、腹圧を高めてから引く',
      'ロックアウトで腰を過度に反らない',
      '重量より完璧なフォームを優先する',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=デッドリフト+フォーム+初心者',
    imageUrl: EX_IMAGES['デッドリフト'],
  },
  {
    name: 'バーベル・ベントオーバーロウ',
    icon: '📐',
    sets: 4,
    reps: '8rep',
    description: '背中全体（広背筋・僧帽筋・菱形筋）に高重量をかけられる。背中の厚みと幅を同時に作る。',
    points: [
      '上体は45〜60度に前傾。背中はフラット',
      'バーをへそに向けて引く（広背筋意識）',
      '肘を背中に近い軌道で引く',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=バーベルベントオーバーロウ+コツ',
    imageUrl: EX_IMAGES['バーベル・ベントオーバーロウ'],
  },
  {
    name: 'ダンベル・ワンハンドロウ',
    icon: '💪',
    sets: 3,
    reps: '10rep（片側）',
    description: '片側ずつ行うことで左右差を修正し、広背筋への収縮を感じやすい。',
    points: [
      'ベンチに膝と手をついて体を安定',
      'ダンベルを腰骨に向けて引く',
      '引いたところで1秒止める',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルロウ+広背筋+コツ',
    imageUrl: EX_IMAGES['ダンベル・ワンハンドロウ'],
  },
  {
    name: 'バーベル・グッドモーニング',
    icon: '🎯',
    sets: 3,
    reps: '12rep',
    description: '脊柱起立筋・ハムストリングスを鍛え、デッドリフトのサポート筋を強化。背中の下部の厚みを作る。',
    points: [
      'バーを僧帽筋上に担ぐ（軽めで行う）',
      '背中まっすぐのまま股関節から前傾',
      'ハムストリングスのストレッチを感じる深さまで',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=バーベルグッドモーニング+脊柱起立筋',
    imageUrl: EX_IMAGES['バーベル・グッドモーニング'],
  },
  {
    name: 'バーベル・カール',
    icon: '🌀',
    sets: 3,
    reps: '10rep',
    description: '上腕二頭筋を直接鍛え、腕の太さを作る。背中デーの仕上げに。',
    points: [
      '肘を固定し、体の揺れを使わない',
      '最高点で1秒キープ',
      'ゆっくり（3秒）下ろす',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=バーベルカール+上腕二頭筋+フォーム',
    imageUrl: EX_IMAGES['バーベル・カール'],
  },
];

const chestExercises: Exercise[] = [
  {
    name: 'バーベル・ベンチプレス',
    icon: '💥',
    sets: 4,
    reps: '8rep ／ メイン種目',
    description: '胸板の厚みを作る最基本種目。大胸筋・三角筋前部・上腕三頭筋を総動員。',
    points: [
      'グリップは肩幅の1.5倍程度',
      '肩甲骨を寄せてアーチを作り、肩を守る',
      'バーを乳首あたりに下ろす',
      '肘を45度（体との角度）で下ろす',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=バーベルベンチプレス+正しいフォーム',
    imageUrl: EX_IMAGES['バーベル・ベンチプレス'],
  },
  {
    name: 'ダンベル・インクラインプレス',
    icon: '📈',
    sets: 3,
    reps: '10rep',
    description: '大胸筋上部を鍛え、胸板の上部の厚みと服を着たときのシルエットを作る。',
    points: [
      'ベンチ角度は30〜45度',
      'ダンベルを鎖骨〜乳首の上あたりに下ろす',
      '押すときに内側に絞るイメージ',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=インクラインダンベルプレス+大胸筋上部',
    imageUrl: EX_IMAGES['ダンベル・インクラインプレス'],
  },
  {
    name: 'ダンベル・フライ',
    icon: '🦋',
    sets: 3,
    reps: '12rep',
    description: '大胸筋を最大ストレッチさせる種目。胸の内側の輪郭と伸展域での筋肥大に効果的。',
    points: [
      '肘を少し曲げた状態を保ったまま弧を描く',
      '下げすぎて肩が痛い場合は浅めに',
      '胸の上で絞るように閉じる',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルフライ+大胸筋+コツ',
    imageUrl: EX_IMAGES['ダンベル・フライ'],
  },
  {
    name: 'ダンベル・サイドレイズ（肩補助）',
    icon: '↔️',
    sets: 3,
    reps: '15rep',
    description: '週2回目の肩中部への刺激。月曜より軽めでポンプを狙う。',
    points: [
      '月曜より少し軽い重量でコントロール重視',
      '15〜20repで筋肉に血を集める',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルサイドレイズ+コツ',
    imageUrl: EX_IMAGES['ダンベル・サイドレイズ（肩補助）'],
  },
  {
    name: 'ディップス（自重）',
    icon: '🤸',
    sets: 3,
    reps: '最大回数',
    description: '大胸筋下部と三頭筋を仕上げる締め種目。',
    points: [
      '前傾すると胸、垂直だと三頭筋に入る',
      '肘が外に開きすぎないよう注意',
      'できるなら加重（ダンベルを足で挟む）',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ディップス+大胸筋+フォーム',
    imageUrl: EX_IMAGES['ディップス（自重）'],
  },
];

const freeWeightLegExercises: Exercise[] = [
  {
    name: 'バーベル・スクワット',
    icon: '👑',
    sets: 4,
    reps: '8rep ／ 最重要種目',
    description: '脚の王様種目。大腿四頭筋・大臀筋・ハムストリングスを全部動員。全身の成長ホルモン分泌も促進。',
    points: [
      'バーは僧帽筋上（ハイバー）に担ぐ',
      '足幅は肩幅程度、つま先は30度外向き',
      '太ももが床と平行になるまで下げる',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=バーベルスクワット+正しいフォーム+初心者',
    imageUrl: EX_IMAGES['バーベル・スクワット'],
  },
  {
    name: 'バーベル・ヒップスラスト',
    icon: '🍑',
    sets: 4,
    reps: '10rep',
    description: '大臀筋を最大収縮させる最強の種目。お尻の丸みと張りを作り、ラグビー選手的な下半身を構築。',
    points: [
      '肩甲骨をベンチの端に固定',
      '腰を上げたところでお尻を2秒キュッと締める',
      '腰を反らせすぎず骨盤を水平に',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=バーベルヒップスラスト+大臀筋+フォーム',
    imageUrl: EX_IMAGES['バーベル・ヒップスラスト'],
  },
  {
    name: 'ダンベル・ランジ',
    icon: '🚶',
    sets: 3,
    reps: '12rep（片脚）',
    description: '左右の脚を均等に鍛えつつ、バランス能力も向上させる。',
    points: [
      '踏み込んだ膝が90度になる歩幅',
      '前膝がつま先より前に出ない',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルランジ+フォーム+コツ',
    imageUrl: EX_IMAGES['ダンベル・ランジ'],
  },
  {
    name: 'ルーマニアン・デッドリフト',
    icon: '📉',
    sets: 3,
    reps: '10rep',
    description: 'ハムストリングスをストレッチしながら鍛える。太ももの裏の厚みとお尻の境目を作る。',
    points: [
      '膝は軽く曲げた状態を固定',
      'ハムの引っ張りを感じる深さまで前傾',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ルーマニアンデッドリフト+ハムストリングス',
    imageUrl: EX_IMAGES['ルーマニアン・デッドリフト'],
  },
  {
    name: 'カーフレイズ（バーベル）',
    icon: '⬆️',
    sets: 4,
    reps: '15〜20rep',
    description: 'ふくらはぎを鍛えて脚全体のシルエットを完成させる締め種目。',
    points: [
      '踵が完全に下がりきるまでストレッチ',
      '最高点で2秒キープ',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=カーフレイズ+バーベル+ふくらはぎ',
    imageUrl: EX_IMAGES['カーフレイズ（バーベル）'],
  },
];

const bFriExercises: Exercise[] = [
  {
    name: 'デッドリフト',
    icon: '⚓',
    sets: 4,
    reps: '5rep ／ 最重要種目',
    description: '全身の筋肉を動員する最強の種目。背中の厚みとVシェイプの核心。',
    points: [
      'バーはすねの前（ほぼ密着）、足幅は腰幅',
      '背中をフラットに保ち、腹圧を高めてから引く',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=デッドリフト+フォーム+初心者',
    imageUrl: EX_IMAGES['デッドリフト'],
  },
  {
    name: 'バーベル・ベントオーバーロウ',
    icon: '📐',
    sets: 3,
    reps: '8rep',
    description: '背中全体に高重量をかけられる。背中の厚みと幅を同時に作る。',
    points: [
      '上体は45〜60度に前傾。背中はフラット',
      'バーをへそに向けて引く（広背筋意識）',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=バーベルベントオーバーロウ+コツ',
    imageUrl: EX_IMAGES['バーベル・ベントオーバーロウ'],
  },
  {
    name: 'バーベル・ベンチプレス',
    icon: '💥',
    sets: 4,
    reps: '8rep',
    description: '胸板の厚みを作る。背中デーと合わせることで上半身を一気に鍛える。',
    points: [
      '肩甲骨を寄せてアーチを作り、肩を守る',
      'バーを乳首あたりに下ろす',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=バーベルベンチプレス+正しいフォーム',
    imageUrl: EX_IMAGES['バーベル・ベンチプレス'],
  },
  {
    name: 'ダンベル・ワンハンドロウ',
    icon: '💪',
    sets: 3,
    reps: '10rep（片側）',
    description: '広背筋への収縮を感じやすい。左右差の修正にも効果的。',
    points: ['腰骨に向けて引き、引いたところで1秒止める'],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルロウ+広背筋+コツ',
    imageUrl: EX_IMAGES['ダンベル・ワンハンドロウ'],
  },
  {
    name: 'ダンベル・フライ',
    icon: '🦋',
    sets: 3,
    reps: '12rep ／ 締め種目',
    description: '胸を最大ストレッチして仕上げる。胸の内側の輪郭を強調。',
    points: [
      '肘を少し曲げた状態で弧を描く',
      '胸の上で絞るように閉じる',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルフライ+大胸筋+コツ',
    imageUrl: EX_IMAGES['ダンベル・フライ'],
  },
];

const bSunExercises: Exercise[] = [
  {
    name: 'スミスマシン・ショルダープレス',
    icon: '🤖',
    sets: 4,
    reps: '10rep',
    description: 'スミスマシンで安定した軌道を確保しながら三角筋全体を追い込む。',
    points: [
      '座って行うと安定感が増す',
      'バーを顎の高さまで下げる',
      '最大収縮で1秒キープ',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=スミスマシンショルダープレス+三角筋',
    imageUrl: EX_IMAGES['スミスマシン・ショルダープレス'],
  },
  {
    name: 'マシン・サイドレイズ（またはダンベル）',
    icon: '↔️',
    sets: 4,
    reps: '15rep',
    description: '週2回目の三角筋中部刺激。ポンプを意識して軽めでテンポよく。',
    points: [
      '月曜より軽めの重量で高rep',
      '肩に血を集めてパンプを感じる',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ダンベルサイドレイズ+コツ',
    imageUrl: EX_IMAGES['マシン・サイドレイズ（またはダンベル）'],
  },
  {
    name: 'レッグプレス',
    icon: '🦿',
    sets: 4,
    reps: '12rep',
    description: '木曜スクワットの補完として大腿四頭筋・大臀筋をさらに追い込む。',
    points: [
      '足幅やや広め、つま先は30度外向き',
      '腰をシートから浮かさない',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=レッグプレス+やり方+コツ',
    imageUrl: EX_IMAGES['レッグプレス'],
  },
  {
    name: 'レッグカール',
    icon: '🔩',
    sets: 3,
    reps: '12rep',
    description: 'ハムストリングスをマシンで単独に追い込む。木曜との相乗効果で太ももの裏を強化。',
    points: [
      '最大収縮で1〜2秒キープ',
      'ゆっくり（3秒）伸ばして戻す',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=レッグカール+フォーム',
    imageUrl: EX_IMAGES['レッグカール'],
  },
  {
    name: 'ラットプルダウン',
    icon: '🏄',
    sets: 3,
    reps: '10rep ／ ボーナス種目',
    description: '広背筋の幅を作るVシェイプの主役種目。マシンジムならではのメニュー。',
    points: [
      '広めグリップ（肩幅の1.5倍程度）',
      '胸を張り、バーを鎖骨〜胸の上部に引く',
      '肩甲骨を下げながら引くイメージ',
    ],
    youtubeUrl: 'https://www.youtube.com/results?search_query=ラットプルダウン+広背筋+フォーム',
    imageUrl: EX_IMAGES['ラットプルダウン'],
  },
];

export const PATTERN_A: TrainingPattern = {
  id: 'a',
  name: 'Pattern A',
  description: '火曜：マシンジム週',
  schedule: [
    {
      day: '月',
      label: 'mon',
      muscleGroup: '肩',
      gymType: 'free',
      isRest: false,
      headerIcon: '💪',
      headerTitle: '月曜：肩（三角筋）',
      headerVolume: '5種目 ／ 約60〜75分',
      exercises: shoulderExercises,
    },
    {
      day: '火',
      label: 'tue',
      muscleGroup: '脚★',
      gymType: 'machine',
      isRest: false,
      headerIcon: '🦵',
      headerTitle: '火曜：脚（マシン集中）',
      headerVolume: '5種目 ／ 約60〜70分',
      exercises: machineLegExercises,
    },
    {
      day: '水',
      label: 'wed',
      muscleGroup: '休み',
      gymType: 'rest',
      isRest: true,
      restIcon: '😴',
      restTitle: '水曜：完全休養日',
      restMessage: '筋肉は休んでいる間に育ちます。\n7000〜9000歩の歩行 + 食後10分散歩で\n代謝を維持しましょう。',
      exercises: [],
    },
    {
      day: '木',
      label: 'thu',
      muscleGroup: '背中',
      gymType: 'free',
      isRest: false,
      headerIcon: '🏋️',
      headerTitle: '木曜：背中 + 二頭筋',
      headerVolume: '5種目 ／ 約60〜75分',
      exercises: backBicepExercises,
    },
    {
      day: '金',
      label: 'fri',
      muscleGroup: '胸',
      gymType: 'free',
      isRest: false,
      headerIcon: '🫁',
      headerTitle: '金曜：胸 + 肩（補助）',
      headerVolume: '5種目 ／ 約60分',
      exercises: chestExercises,
    },
    {
      day: '土',
      label: 'sat',
      muscleGroup: '休み',
      gymType: 'rest',
      isRest: true,
      restIcon: '🚶',
      restTitle: '土曜：アクティブレスト',
      restMessage: '積極的に外出し、7000〜9000歩を歩く日。\n食後の10分散歩も忘れずに。\n筋肉の回復と代謝維持を両立。',
      exercises: [],
    },
    {
      day: '日',
      label: 'sun',
      muscleGroup: '休み',
      gymType: 'rest',
      isRest: true,
      restIcon: '🛌',
      restTitle: '日曜：完全休養日',
      restMessage: '週の疲労をリセット。\n来週のトレーニングに備えて\nしっかり睡眠・栄養補給を。',
      exercises: [],
    },
  ],
};

export const PATTERN_B: TrainingPattern = {
  id: 'b',
  name: 'Pattern B',
  description: '日曜：マシンジム週',
  schedule: [
    {
      day: '月',
      label: 'mon',
      muscleGroup: '肩',
      gymType: 'free',
      isRest: false,
      headerIcon: '💪',
      headerTitle: '月曜：肩（三角筋）',
      headerVolume: '5種目 ／ 約60〜75分',
      exercises: shoulderExercises,
    },
    {
      day: '火',
      label: 'tue',
      muscleGroup: '休み',
      gymType: 'rest',
      isRest: true,
      restIcon: '🚶',
      restTitle: '火曜：アクティブレスト',
      restMessage: '7000〜9000歩の歩行を目標に。\n食後の10分散歩で代謝を維持。',
      exercises: [],
    },
    {
      day: '水',
      label: 'wed',
      muscleGroup: '休み',
      gymType: 'rest',
      isRest: true,
      restIcon: '😴',
      restTitle: '水曜：完全休養日',
      restMessage: '月〜火の疲労をリセット。\n木曜のトレーニングに備える。',
      exercises: [],
    },
    {
      day: '木',
      label: 'thu',
      muscleGroup: '脚',
      gymType: 'free',
      isRest: false,
      headerIcon: '🦵',
      headerTitle: '木曜：脚（フリーウェイト）',
      headerVolume: '5種目 ／ 約65〜75分',
      exercises: freeWeightLegExercises,
    },
    {
      day: '金',
      label: 'fri',
      muscleGroup: '背中+胸',
      gymType: 'free',
      isRest: false,
      headerIcon: '🏋️',
      headerTitle: '金曜：背中 + 胸',
      headerVolume: '5種目 ／ 約65分',
      exercises: bFriExercises,
    },
    {
      day: '土',
      label: 'sat',
      muscleGroup: '休み',
      gymType: 'rest',
      isRest: true,
      restIcon: '🚶',
      restTitle: '土曜：アクティブレスト',
      restMessage: '7000〜9000歩の歩行を目標に。\n日曜のマシンジムに備えて回復を優先。',
      exercises: [],
    },
    {
      day: '日',
      label: 'sun',
      muscleGroup: '肩+脚★',
      gymType: 'machine',
      isRest: false,
      headerIcon: '★',
      headerTitle: '日曜：肩 + 脚（マシン）',
      headerVolume: '5種目 ／ 約60〜70分',
      exercises: bSunExercises,
    },
  ],
};
